version: '3.3'
services:
  zookeeper:
    image: zookeeper:3.6.1
    restart: on-failure:5
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/logs:/datalog"
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: on-failure:5
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.8.178
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.3.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms128M"
      KAFKA_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka:/kafka
    depends_on:
      - zookeeper
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    restart: on-failure:5
    ports:
      - "9090:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 750M
    depends_on:
      - zookeeper
      - kafka